### ISSUE TITLE
Use auth.json

### ISSUE THREAD

**Issue by chrisvanpatten** [junaidbhura/composer-wp-pro-plugins#8]
Composer provides support for a file for holding authentication keys, `auth.json`. [It's typically used for basic auth](https://getcomposer.org/doc/articles/http-basic-authentication.md) but can also be used for [GitHub/GitLab auth](https://www.previousnext.com.au/blog/managing-composer-github-access-personal-access-tokens).

It should be possible to pull config values from that file with something like…

```
$config = $this->composer->getConfig();

$config->get( 'my-key-in-auth-json' );
```

This would allow you to avoid the `.env` dependency while leveraging a native Composer mechanism.

**Comment by junaidbhura** [comment]
Hey @chrisvanpatten continuing the conversation from #9 here:

Again, I really appreciate all the effort and time you've put into this!

Unfortunately, I've decided to close this issue and pull request at this time for the following reasons:

1. I think keeping the .env file and the way it currently works would serve the purpose of this plugin the best, because it works closely with the Bedrock architecture. It would also preserve backwards compatibility
1. It is much easier to enter key-value pairs as environment variables (for example in a CI environment)
1. I'm going to do a bit of a refactor pretty soon, and add a class for EDD plugins which will be inherited, rather than a method within `Http` like you have in your PR

I'd encourage you to open issues for individual items and have a discussion on the direction to take, and then submit a pull request. Thanks again, and apologies.

**Comment by chrisvanpatten** [comment]
@junaidbhura Thanks for your comment. It's likely that I'll actually build a new plugin with an alternative approach, in order to support the work I'm doing over in https://github.com/TomodomoCo/wp-packages-repo.

Appreciate the reply.

**Comment by junaidbhura** [comment]
Sure no worries, @chrisvanpatten . Please feel free to fork this repository!
